In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = pd.read_csv('insurance_Example_1.csv')              # CSV file for this code 'Example_1.py'

In [ ]:
data

# EDA  -- Exploratory Data Analysis

In [ ]:
data.shape

In [ ]:
data.head()

In [ ]:
data.info()

In [ ]:
data.describe()                                                      # function only describe numeric values, not string vlaues

In [ ]:
data.isnull().sum()                                             # To find null values

In [ ]:
data.columns

In [ ]:
numeric_columns = ['age',  'bmi', 'children', 'charges']              # This list have column names only not the values

In [ ]:
for col in numeric_columns:
    plt.figure(figsize=(6,4))
    sns.histplot(data[col], kde=True, bins=20)                                    # kde is to see curve as well along with normal histogram
                                                                                  # data[col] to get only that column value from the data we have in 'data' variable

### Observation: 
### here we can observe that many people are between age 18 to 20 so definatey they will have less insurance amount (Right skewed distribution), thus for many people we have less insurance amount in the histogram. Also many people have 0 children because of that and BMI is normally distributed.

In [ ]:
sns.countplot(x=data['children'])

In [ ]:
sns.countplot(x=data['sex'])

In [ ]:
sns.countplot(x=data['smoker'])

### A box plot is mainly used in Exploratory Data Analysis (EDA) to understand the distribution of numerical data and especially to identify outliers.

In [ ]:
for col in numeric_columns:
    plt.figure(figsize=(6,4))
    sns.boxplot(x=data[col])

### Heat map is to view the correlation

In [ ]:
plt.figure(figsize = (8,6))
sns.heatmap(data.corr(numeric_only=True),annot=True)                                    # correlation works only for numeric values thus numeric_only=True
                                                                                      # annot=True for getting the correlation value on each box

# Data Cleaning and Preprocessing

In [ ]:
data_cleaned = data.copy()

In [ ]:
data_cleaned.head()

In [ ]:
data_cleaned.shape

In [ ]:
data_cleaned.drop_duplicates(inplace = True)

In [ ]:
data_cleaned.shape                               # 1 duplcate row was present

In [ ]:
data_cleaned.isnull().sum()

In [ ]:
data_cleaned.dtypes

In [ ]:
data_cleaned['sex'].value_counts()

### Labelled encoding

In [ ]:
data_cleaned['sex'] = data_cleaned['sex'].map({"male" : 0, "female" : 1})

In [ ]:
data_cleaned.head()

In [ ]:
data_cleaned['smoker'].value_counts()

In [ ]:
data_cleaned['smoker'] = data_cleaned['smoker'].map({"no" : 0, "yes" : 1})

In [ ]:
data_cleaned.head()

In [ ]:
data_cleaned.rename(columns = {'sex' : 'is_female', 'smoker' : 'is_smoker'}, inplace=True)

In [ ]:
data_cleaned.head()

In [ ]:
data_cleaned['region'].value_counts()

### one hot encoding

In [ ]:
data_cleaned = pd.get_dummies(data_cleaned, columns = ['region'])                # get_dummies gives dummy columns for the column mentioned

In [ ]:
data_cleaned.head()

In [ ]:
data_cleaned = data_cleaned.astype(int)

In [ ]:
data_cleaned.head()                               # All columns converted to integer

In [ ]:
data_cleaned.dtypes

# Feature Engineering

In [ ]:
sns.histplot(data_cleaned['bmi'])

In [ ]:
data_cleaned['bmi_category'] = pd.cut(                                         # pd.cut() function in Pandas is used to bin continuous numeric data into discrete intervals (categories)
    data_cleaned['bmi'], 
    bins=[0,18.5,24.9,29.9,float('inf')],                                      # Based on BMI categories
    labels=['Underweight', 'Normal', 'Overweight', 'Obese']
)

In [ ]:
data_cleaned.head()

In [ ]:
data_cleaned = pd.get_dummies(data_cleaned, columns = ['bmi_category'])

In [ ]:
data_cleaned

In [ ]:
data_cleaned = data_cleaned.astype(int)

In [179]:
data_cleaned.head()

,age,is_female,bmi,children,is_smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest,bmi_category_Underweight,bmi_category_Normal,bmi_category_Overweight,bmi_category_Obese
0,19,1,27,0,1,16884,0,0,0,1,0,0,1,0
1,18,0,33,1,0,1725,0,0,1,0,0,0,0,1
2,28,0,33,3,0,4449,0,0,1,0,0,0,0,1
3,33,0,22,0,0,21984,0,1,0,0,0,1,0,0
4,32,0,28,0,0,3866,0,1,0,0,0,0,1,0

### Feature scaling

#### Feature scaling is done to bring all data features into a consistent numerical range so that no single feature dominates the machine learning model just because it has larger values. 
#### It Improves Distance-Based Models : like K-Nearest Neighbors (KNN) and K-Means Clustering. 
#### Speeds Up Gradient Descent : Models trained via gradient descent (such as linear regression, logistic regression, and neural networks) converge much faster with it.

In [180]:
data_cleaned.columns

Index(['age', 'is_female', 'bmi', 'children', 'is_smoker', 'charges',
       'region_northeast', 'region_northwest', 'region_southeast',
       'region_southwest', 'bmi_category_Underweight', 'bmi_category_Normal',
       'bmi_category_Overweight', 'bmi_category_Obese'],
      dtype='str')

In [181]:
from sklearn.preprocessing import StandardScaler
cols = ['age','bmi','children']
scaler = StandardScaler()

data_cleaned[cols] = scaler.fit_transform(data_cleaned[cols])

In [182]:
data_cleaned.head()

,age,is_female,bmi,children,is_smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest,bmi_category_Underweight,bmi_category_Normal,bmi_category_Overweight,bmi_category_Obese
0,-1.440418,1,-0.517949,-0.909234,1,16884,0,0,0,1,0,0,1,0
1,-1.511647,0,0.462463,-0.079442,0,1725,0,0,1,0,0,0,0,1
2,-0.799350,0,0.462463,1.580143,0,4449,0,0,1,0,0,0,0,1
3,-0.443201,0,-1.334960,-0.909234,0,21984,0,1,0,0,0,1,0,0
4,-0.514431,0,-0.354547,-0.909234,0,3866,0,1,0,0,0,0,1,0

# Feature Extraction/ Selection

#### Pearson's correlation coefficient (r) measures the strength and direction of the linear relationship between two continuous variables

In [185]:
from scipy.stats import pearsonr

selected_features = ['age', 'is_female', 'bmi', 'children', 'is_smoker',
       'region_northeast', 'region_northwest', 'region_southeast',
       'region_southwest', 'bmi_category_Underweight', 'bmi_category_Normal',
       'bmi_category_Overweight', 'bmi_category_Obese']

correlations = {
    feature : pearsonr(data_cleaned[feature], data_cleaned['charges'])[0]      # pearsonr() returns two values, [0] → correlation, [1] → p-value, here we want only correlation
    for feature in selected_features
}

correlation_data = pd.DataFrame(list(correlations.items()), columns = ['Feature', 'Pearson Correlation'])
correlation_data.sort_values(by='Pearson Correlation', ascending = False)

                     Feature  Pearson Correlation
4                  is_smoker             0.787234
0                        age             0.298309
12        bmi_category_Obese             0.200348
2                        bmi             0.196236
7           region_southeast             0.073577
3                   children             0.067390
5           region_northeast             0.005946
6           region_northwest            -0.038695
8           region_southwest            -0.043637
9   bmi_category_Underweight            -0.050599
1                  is_female            -0.058046
10       bmi_category_Normal            -0.104042
11   bmi_category_Overweight            -0.120601

In [ ]:
# We can find is_smoker is highly correlated

#### Correlation :
#### Two types  : Negetive or Positive Correlation
#### A positive correlation means two variables move in the same direction, while a negative correlation means they move in opposite directions.
#### Strength Guidelines :
#### 0.50 to 1.00 (or -0.50 to -1.00): Strong correlation.
#### 0.20 to 0.49 (or -0.20 to -0.49): Moderate correlation.
#### 0.01 to 0.19 (or -0.01 to -0.19): Weak correlation.

In [186]:
##

#### Chi-Square Test (χ²) 

#### The Chi-Square test is a statistical test mainly used to determine whether two categorical variables are related/associated with each other.

#### For example, in an insurance dataset:

#### smoker → categorical (yes/no)
#### region → categorical (north/south/east/west)

#### You can use a Chi-Square test to ask:

#### Is smoking status associated with region?

In [187]:
categorical_features = ['is_female','is_smoker',
       'region_northeast', 'region_northwest', 'region_southeast',
       'region_southwest', 'bmi_category_Underweight', 'bmi_category_Normal',
       'bmi_category_Overweight', 'bmi_category_Obese']

In [190]:
from scipy.stats import chi2_contingency

alpha = 0.05

data_cleaned['charges_bin'] = pd.qcut(data_cleaned['charges'], q=4, labels=False)
chi2_results = {}

for col in categorical_features :
    contingency = pd.crosstab(data_cleaned[col], data_cleaned['charges_bin'])
    chi2_stat, p_val, _, _ = chi2_contingency(contingency)
    decision = "Reject Null (Keep Feature)" if p_val < alpha else "Accept Null (Drop Feature)"
    chi2_results[col] = {
    'chi2_statistic' : chi2_stat,
    'p_value' : p_val,
    'Decision'  : decision
    }


chi2_data = pd.DataFrame(chi2_results).T
chi2_data = chi2_data.sort_values(by='p_value')
chi2_data

                         chi2_statistic   p_value                    Decision
is_smoker                    848.219178       0.0  Reject Null (Keep Feature)
region_southeast              15.998167  0.001135  Reject Null (Keep Feature)
is_female                     10.258784   0.01649  Reject Null (Keep Feature)
bmi_category_Obese             8.515711  0.036473  Reject Null (Keep Feature)
region_northeast               6.438442  0.092122  Accept Null (Drop Feature)
region_southwest               5.091893  0.165191  Accept Null (Drop Feature)
bmi_category_Overweight         4.25149  0.235557  Accept Null (Drop Feature)
bmi_category_Normal            3.708088   0.29476  Accept Null (Drop Feature)
bmi_category_Underweight        3.37403  0.337471  Accept Null (Drop Feature)
region_northwest                1.13424  0.768815  Accept Null (Drop Feature)

In [192]:
final_data = data_cleaned[['age', 'is_female', 'bmi', 'children', 'is_smoker', 'charges',
        'region_southeast','bmi_category_Obese']]

In [193]:
final_data.head()

,age,is_female,bmi,children,is_smoker,charges,region_southeast,bmi_category_Obese
0,-1.440418,1,-0.517949,-0.909234,1,16884,0,0
1,-1.511647,0,0.462463,-0.079442,0,1725,1,1
2,-0.799350,0,0.462463,1.580143,0,4449,1,1
3,-0.443201,0,-1.334960,-0.909234,0,21984,0,0
4,-0.514431,0,-0.354547,-0.909234,0,3866,0,0